openapi: 3.0.0
info:
  title: We Dream
  contact: {}
  version: '1.0'
servers:
- url: https://we-dream.herokuapp.com/api/v1
  variables: {}
paths:
  /login:
    post:
      tags:
      - Auth
      summary: login
      operationId: login
      parameters:
      - name: email
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: ravi@gmail.com
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginrequest'
            example:
              email: starkbisht@gmail.com
              password: starkabc
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /register:
     post:
      tags:
      - Auth
      summary: signup
      operationId: signup
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signuprequest'
            example:
              name: stark bisht
              email: starkbisht@gmail.com
              password: starkabc
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      paths:
  /job:
    get:
      tags:
      - Jobs
      summary: Get all jobs
      operationId: Getalljobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      
    /job/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
      - Jobs
      summary: Get job
      operationId: Getjob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Jobs
      summary: Create job
      operationId: Createjob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatejobRequest'
            example:
              company: HDFC
              position: Java Developer
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  
    patch:
      tags:
      - Jobs
      summary: Update job
      operationId: Updatejob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatejobRequest'
            example:
              company: Meta
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  
    delete:
      tags:
      - Jobs
      summary: Delete job
      operationId: Deletejob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    loginrequest:
      title: loginrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: starkbisht@gmail.com
        password: starkabc
    signuprequest:
      title: signuprequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: stark bisht
        email: starkbisht@gmail.com
        password: starkabc
    CreatejobRequest:
      title: CreatejobRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: HDFC
        position: Java Developer
    UpdatejobRequest:
      title: UpdatejobRequest
      required:
      - company
      type: object
      properties:
        company:
          type: string
      example:
        company: Meta
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
- httpBearer: []
tags:
- name: Auth
- name: Jobs